export default [{
  id: 'components',
  pid: '',
  title: '组件列表',
  icon: 'appstore-o',
  route: ''
}, {
  id: 'components.image',
  pid: 'components',
  title: 'Image',
  route: '/component/image'
}, {
  id: 'components.imageViewer',
  pid: 'components',
  title: 'ImageViewer',
  route: ''
}, {
  id: 'components.detailPanel',
  pid: 'components',
  title: 'DetailPanel',
  route: ''
}, {
  id: 'user',
  pid: '',
  title: '用户管理',
  icon: 'user',
  route: '/user'
}, {
  id: 'user.account',
  pid: 'user',
  title: '账号管理',
  icon: '',
  route: '/user/account'
}, {
  id: 'user.role',
  pid: 'user',
  title: '角色管理',
  icon: '',
  route: '/user/role'
}, {
  id: 'statistics',
  pid: '',
  title: '数据统计',
  icon: 'area-chart',
  route: '/statistics'
}, {
  id: 'operationLog',
  pid: '',
  title: '操作日志',
  icon: 'book',
  route: '/operationLog',
}];